// Traffic control data for Incheon International Airport Expressway
const constructionData = [
    {
        "inputdate": "2025-07-28",
        "blockdate": "2025-07-29",
        "const_name": "인천국제공항영업소 톨게이트 노후 시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "인천공항TG",
        "chadantime": "",
        "chadan": "[\"영업소\"]",
        "workers": 5,
        "signcar": 1,
        "workcar": 1,
        "employee": "이현원",
        "employeephone": "",
        "contractee": "만경건설",
        "sitemanager": "조민식",
        "smcellphone": "010-2755-7777"
    },
    {
        "inputdate": "2025-07-28",
        "blockdate": "2025-07-29",
        "const_name": "인천국제공항영업소 톨게이트 노후 시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "인천공항TG",
        "chadantime": "",
        "chadan": "[\"영업소\"]",
        "workers": 5,
        "signcar": 1,
        "workcar": 1,
        "employee": "이현원",
        "employeephone": "",
        "contractee": "만경건설",
        "sitemanager": "조민식",
        "smcellphone": "010-2755-7777"
    },
    {
        "inputdate": "2025-07-28",
        "blockdate": "2025-07-29",
        "const_name": "인천국제공항영업소 톨게이트 노후 시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "인천공항TG",
        "chadantime": "",
        "chadan": "[\"영업소\"]",
        "workers": 5,
        "signcar": 1,
        "workcar": 1,
        "employee": "이현원",
        "employeephone": "",
        "contractee": "만경건설",
        "sitemanager": "조민식",
        "smcellphone": "010-2755-7777"
    },
    {
        "inputdate": "2025-07-28",
        "blockdate": "2025-07-29",
        "const_name": "인천국제공항영업소 톨게이트 노후 시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "인천공항TG",
        "chadantime": "",
        "chadan": "[\"영업소\"]",
        "workers": 5,
        "signcar": 1,
        "workcar": 1,
        "employee": "이현원",
        "employeephone": "",
        "contractee": "만경건설",
        "sitemanager": "조민식",
        "smcellphone": "010-2755-7777"
    },
    {
        "inputdate": "2025-07-28",
        "blockdate": "2025-07-29",
        "const_name": "인천국제공항영업소 톨게이트 노후 시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "인천공항TG",
        "chadantime": "",
        "chadan": "[\"영업소\"]",
        "workers": 5,
        "signcar": 1,
        "workcar": 1,
        "employee": "이현원",
        "employeephone": "",
        "contractee": "만경건설",
        "sitemanager": "조민식",
        "smcellphone": "010-2755-7777"
    },
    {
        "inputdate": "2025-07-29",
        "blockdate": "2025-07-30",
        "const_name": "테스트",
        "direction": "서울방향",
        "ieejung": "서울 20.5",
        "chadantime": "",
        "chadan": "[\"4\",\"갓길\"]",
        "workers": 3,
        "signcar": 1,
        "workcar": 2,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "크로바",
        "sitemanager": "박찬군",
        "smcellphone": "010-2575-1234"
    },
    {
        "inputdate": "2025-07-29",
        "blockdate": "2025-07-30",
        "const_name": "테스트",
        "direction": "서울방향",
        "ieejung": "서울 20.5",
        "chadantime": "",
        "chadan": "[\"4\",\"갓길\"]",
        "workers": 3,
        "signcar": 1,
        "workcar": 2,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "크로바",
        "sitemanager": "박찬군",
        "smcellphone": "010-2575-1234"
    },
    {
        "inputdate": "2025-08-13",
        "blockdate": "2025-08-14",
        "const_name": "교통사고 복구공사",
        "direction": "공항방향",
        "ieejung": "27.4",
        "chadantime": "",
        "chadan": "[\"4차로\",\"갓길\"]",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "크로바",
        "sitemanager": "박찬군",
        "smcellphone": "010-5310-0227"
    },
    {
        "inputdate": "2025-08-13",
        "blockdate": "2025-08-14",
        "const_name": "교통사고 피해시설물 복구공사",
        "direction": "공항방향",
        "ieejung": "27.4",
        "chadantime": "",
        "chadan": "[\"4차로\",\"갓길\"]",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "크로바",
        "sitemanager": "박찬군",
        "smcellphone": "010-2755-7686"
    },
    {
        "inputdate": "2025-08-13",
        "blockdate": "2025-08-14",
        "const_name": "교통사고 복구2",
        "direction": "공항방향",
        "ieejung": "14",
        "chadantime": "",
        "chadan": "1차로, 2차로",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "테스트",
        "employeephone": "",
        "contractee": "테스트",
        "sitemanager": "김현호",
        "smcellphone": "010-2755-7698"
    },
    {
        "inputdate": "2025-08-13",
        "blockdate": "2025-08-14",
        "const_name": "테스트",
        "direction": "공항방향",
        "ieejung": "16.4",
        "chadantime": "",
        "chadan": "1차로, 2차로",
        "workers": 5,
        "signcar": 2,
        "workcar": 2,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "크로바",
        "sitemanager": "김현호",
        "smcellphone": "010-2755-7686"
    },
    {
        "inputdate": "2025-08-13",
        "blockdate": "2025-08-14",
        "const_name": "테스트",
        "direction": "공항방향",
        "ieejung": "16.4",
        "chadantime": "",
        "chadan": "1차로, 2차로",
        "workers": 5,
        "signcar": 2,
        "workcar": 2,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "크로바",
        "sitemanager": "김현호",
        "smcellphone": "010-2755-7686"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "인천국제공항고속도로 차선도색공사",
        "direction": "서울방향",
        "ieejung": "36.5~0.0",
        "chadantime": "",
        "chadan": "1차로, 2차로",
        "workers": 13,
        "signcar": 3,
        "workcar": 4,
        "employee": "김도균",
        "employeephone": "",
        "contractee": "대한로드라인(주)",
        "sitemanager": "문학영 부장",
        "smcellphone": "010-4537-6457"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "설비유지관리 용역",
        "direction": "공항방향",
        "ieejung": "34.0~36.3",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 1,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "대한곤돌라(주)",
        "sitemanager": "홍지환",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "가로등 누전선로 보수공사",
        "direction": "서울방향",
        "ieejung": "11.6K 및 12.6K",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 3,
        "signcar": 0,
        "workcar": 1,
        "employee": "고영우",
        "employeephone": "",
        "contractee": "두복산전",
        "sitemanager": "박상윤 소장",
        "smcellphone": "010-2337-1524"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "설비유지관리용역",
        "direction": "서울방향",
        "ieejung": "11.6~13.4",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "대한곤돌라(주)",
        "sitemanager": "홍지환",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "설비유지관리 용역",
        "direction": "서울방향",
        "ieejung": "11.6~13.4",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "대한곤돌라(주)",
        "sitemanager": "홍지환",
        "smcellphone": "1021243794"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "영종, 방화 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "11.6~13.4",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 0,
        "workcar": 4,
        "employee": "최종",
        "employeephone": "",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "1094283658"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "영종,방화 정밀안전진단",
        "direction": "서울방향",
        "ieejung": "11.6~13.4",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 2,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "1094283658"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "영종,방화 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "11.6~13.4",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "1084474659"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "영종,방화 정밀안전진단",
        "direction": "서울방향",
        "ieejung": "11.6~13.4",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "1084474659"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "영종, 방화 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "33.5~36.5",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "",
        "contractee": "백양엔지니어링",
        "sitemanager": "이명우",
        "smcellphone": "1023925168"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "일반교량 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "32.3~35.3",
        "chadantime": "",
        "chadan": "1차로",
        "workers": 4,
        "signcar": 4,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주",
        "smcellphone": "1055941825"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "일반교량 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "32.3~35.3",
        "chadantime": "",
        "chadan": "2차로, 3차로",
        "workers": 4,
        "signcar": 4,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주",
        "smcellphone": "1055941825"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "신축이음 특별점검",
        "direction": "공항방향",
        "ieejung": "0.0~36.5",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주",
        "smcellphone": "1055941825"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "신축이음 특별점검",
        "direction": "서울방향",
        "ieejung": "0.0~36.5",
        "chadantime": "",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주",
        "smcellphone": "1055941825"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-18",
        "const_name": "도로시설물 보수",
        "direction": "양방향",
        "ieejung": "북인천영업소 광장부",
        "chadantime": "",
        "chadan": "영업소",
        "workers": 16,
        "signcar": 4,
        "workcar": 8,
        "employee": "한상열",
        "employeephone": "",
        "contractee": "상봉이앤씨",
        "sitemanager": "이래원",
        "smcellphone": "010-3805-0234"
    },
    {
        "inputdate": "2025-08-18",
        "blockdate": "2025-08-19",
        "const_name": "테스트",
        "direction": "공항방향",
        "ieejung": "27.4~28.0",
        "chadantime": "",
        "chadan": "1차로, 2차로",
        "workers": 4,
        "signcar": 1,
        "workcar": 3,
        "employee": "김현호",
        "employeephone": "",
        "contractee": "테스트",
        "sitemanager": "테스트",
        "smcellphone": "010-2222-3333"
    },
    {
        "inputdate": "2025-08-19",
        "blockdate": "2025-08-20",
        "const_name": "설비유지관리 용역",
        "direction": "공항방향",
        "ieejung": "34.0~36.3",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 1,
        "workcar": 1,
        "employee": "최종 선임",
        "employeephone": "010-6797-5516",
        "contractee": "대한곤돌라",
        "sitemanager": "홍지환 대리",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-19",
        "blockdate": "2025-08-20",
        "const_name": "설비유지관리 용역",
        "direction": "양방향",
        "ieejung": "11.6K~13.4K",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 2,
        "employee": "최종 선임",
        "employeephone": "010-6797-5516",
        "contractee": "대한곤돌라",
        "sitemanager": "홍지환 대리",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-19",
        "blockdate": "2025-08-20",
        "const_name": "영종, 방화 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 2,
        "employee": "최종 선임",
        "employeephone": "010-6797-5516",
        "contractee": "홍익기술단",
        "sitemanager": "이경수 부장",
        "smcellphone": "010-9428-3658"
    },
    {
        "inputdate": "2025-08-19",
        "blockdate": "2025-08-20",
        "const_name": "영종, 방화 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 2,
        "employee": "최종 선임",
        "employeephone": "010-6797-5516",
        "contractee": "다음기술단",
        "sitemanager": "장건우 차장",
        "smcellphone": "010-8447-4659"
    },
    {
        "inputdate": "2025-08-19",
        "blockdate": "2025-08-20",
        "const_name": "일반교량 정밀안전진단",
        "direction": "양방향",
        "ieejung": "9.0 ~ 공항입구JCRB600",
        "chadantime": "09:00~18:00",
        "chadan": "3차로",
        "workers": 5,
        "signcar": 4,
        "workcar": 2,
        "employee": "최종 선임",
        "employeephone": "010-6797-5516",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주 부장",
        "smcellphone": "010-5594-1825"
    },
    {
        "inputdate": "2025-08-19",
        "blockdate": "2025-08-20",
        "const_name": "신축이음 특별점검",
        "direction": "양방향",
        "ieejung": "0.0~36.5",
        "chadantime": "9:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "최종 선임",
        "employeephone": "010-5797-5516",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주 부장",
        "smcellphone": "010-5594-1825"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "교통사고 피해시설물 복구공사",
        "direction": "공항방향",
        "ieejung": "공항신도시ICRK 400",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "크로바건설",
        "sitemanager": "박찬군",
        "smcellphone": "010-5310-0227"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "교통안전시설 설치공사",
        "direction": "서울방향",
        "ieejung": "2.6",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "투인산업",
        "sitemanager": "박재영 과장",
        "smcellphone": "010-3407-3702"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "교통안전시설 설치공사",
        "direction": "양방향",
        "ieejung": "22.1",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "투인산업",
        "sitemanager": "박재영",
        "smcellphone": "010-3407-3702"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "11.5~12.2",
        "chadantime": "09:00~18:00",
        "chadan": "1차로",
        "workers": 8,
        "signcar": 5,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "032-560-6074",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "1084474659"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "10.3~11.2",
        "chadantime": "21:00~04:00",
        "chadan": "2차로",
        "workers": 4,
        "signcar": 5,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "032-560-6074",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "1084474659"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "영종,방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "032-560-6074",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "1094283658"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "일반교량 정밀안전진단",
        "direction": "양방향",
        "ieejung": "26.2~31.11",
        "chadantime": "09:00~18:00",
        "chadan": "1차로",
        "workers": 4,
        "signcar": 5,
        "workcar": 3,
        "employee": "최종",
        "employeephone": "032-560-6074",
        "contractee": "다산컨설턴트",
        "sitemanager": "김현주",
        "smcellphone": "010-5594-1825"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "설비유지관리 용역",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "032-560-6074",
        "contractee": "대한곤돌라",
        "sitemanager": "홍지환",
        "smcellphone": "1021243794"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "교통사고 피해복구 공사",
        "direction": "서울방향",
        "ieejung": "북인천영업소 상행 2번",
        "chadantime": "09:00~18:00",
        "chadan": "영업소",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "크로바 건설",
        "sitemanager": "박찬군",
        "smcellphone": "010-5310-0227"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "교통사고 피해시설물 복구",
        "direction": "서울방향",
        "ieejung": "27.6",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "크로바건설",
        "sitemanager": "박찬군",
        "smcellphone": "010-5310-0227"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "차선도색",
        "direction": "양방향",
        "ieejung": "전구간 이동작업",
        "chadantime": "09:00~18:00",
        "chadan": "1차로, 2차로, 3차로, 4차로",
        "workers": 13,
        "signcar": 3,
        "workcar": 4,
        "employee": "김도균",
        "employeephone": "010-3117-2297",
        "contractee": "대한로드라인",
        "sitemanager": "문학영",
        "smcellphone": "1045376457"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "인천국제공항고속도로 인프라구축 광간선망공사",
        "direction": "공항방향",
        "ieejung": "7.8~10.2",
        "chadantime": "09:30~17:30",
        "chadan": "갓길",
        "workers": 8,
        "signcar": 2,
        "workcar": 3,
        "employee": "정호 수석",
        "employeephone": "010-3301-1801",
        "contractee": "파워텔레콤",
        "sitemanager": "신영수",
        "smcellphone": "010-9551-3738"
    },
    {
        "inputdate": "2025-08-20",
        "blockdate": "2025-08-21",
        "const_name": "도로시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "북인천영업소 광장부",
        "chadantime": "19:00~06:00",
        "chadan": "1차로",
        "workers": 16,
        "signcar": 4,
        "workcar": 8,
        "employee": "한상열 수석",
        "employeephone": "010-8916-1430",
        "contractee": "상봉이앤씨",
        "sitemanager": "이래원 소장",
        "smcellphone": "010-3805-0234"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "차선도색공사",
        "direction": "양방향",
        "ieejung": "전구간 이동작업",
        "chadantime": "09:00~18:00",
        "chadan": "1차로, 2차로, 3차로, 4차로",
        "workers": 13,
        "signcar": 3,
        "workcar": 4,
        "employee": "김도균",
        "employeephone": "01031172297",
        "contractee": "대한로드라인",
        "sitemanager": "문학영",
        "smcellphone": "01045376457"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "인천국제공항고속도로 인프라구축 광간선망공사",
        "direction": "공항방향",
        "ieejung": "10.2k~7.8km 인천공항 방향",
        "chadantime": "09:30 ~ 17:30",
        "chadan": "갓길",
        "workers": 8,
        "signcar": 2,
        "workcar": 3,
        "employee": "정호",
        "employeephone": "010-3301-1801",
        "contractee": "파워텔레콤",
        "sitemanager": "신영수",
        "smcellphone": "010-9551-3738"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-25",
        "const_name": "인천국제공항고속도로 인프라구축 광간선망공사",
        "direction": "공항방향",
        "ieejung": "10.2k~7.8km 인천공항 방향",
        "chadantime": "09:30 ~ 17:30",
        "chadan": "갓길",
        "workers": 8,
        "signcar": 2,
        "workcar": 3,
        "employee": "정호",
        "employeephone": "010-3301-1801",
        "contractee": "파워텔레콤",
        "sitemanager": "신영수",
        "smcellphone": "010-9551-3738"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "설비유지관리 용역",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "대한곤돌라",
        "sitemanager": "홍지환",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "영종, 방화 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "010-9428-3658"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "영종,방화 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4k",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "010-8447-4659"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "울타리설치(철거 포함) 공사",
        "direction": "공항방향",
        "ieejung": "18.0K~19.0K",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "유재석 수석",
        "employeephone": "010-3733-3674",
        "contractee": "노아산업",
        "sitemanager": "조익서",
        "smcellphone": "010-4384-0851"
    },
    {
        "inputdate": "2025-08-21",
        "blockdate": "2025-08-22",
        "const_name": "`25~`26 한국전력인천본부 김포전력지사 지중송전공사",
        "direction": "공항방향",
        "ieejung": "11.6K, 12.3K, 12.7K, 13.4K",
        "chadantime": "10:30~12:30",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "유재석 수석",
        "employeephone": "010-3733-3674",
        "contractee": "(주) 호명",
        "sitemanager": "김주현",
        "smcellphone": "010-5302-2252"
    },
    {
        "inputdate": "2025-08-22",
        "blockdate": "2025-08-25",
        "const_name": "인천국제공항고속도로 인프라구축 광간선망공사",
        "direction": "공항방향",
        "ieejung": "10.2k~7.8km 인천공항 방향",
        "chadantime": "09:30 ~ 17:30",
        "chadan": "갓길",
        "workers": 8,
        "signcar": 2,
        "workcar": 3,
        "employee": "정호",
        "employeephone": "010-3301-1801",
        "contractee": "파워텔레콤",
        "sitemanager": "신영수",
        "smcellphone": "010-9551-3738"
    },
    {
        "inputdate": "2025-08-22",
        "blockdate": "2025-08-25",
        "const_name": "차선도색공사",
        "direction": "양방향",
        "ieejung": "전구간 이동작업",
        "chadantime": "09:00~18:00",
        "chadan": "1차로, 2차로, 3차로, 4차로",
        "workers": 13,
        "signcar": 3,
        "workcar": 4,
        "employee": "김도균",
        "employeephone": "01031172297",
        "contractee": "대한로드라인",
        "sitemanager": "문학영",
        "smcellphone": "01045376457"
    },
    {
        "inputdate": "2025-08-22",
        "blockdate": "2025-08-25",
        "const_name": "설비유지관리 용역",
        "direction": "공항방향",
        "ieejung": "34.0~36.5k",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 1,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "대한곤돌라(주)",
        "sitemanager": "홍지환",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-22",
        "blockdate": "2025-08-25",
        "const_name": "영종,방화 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "010-8447-4659"
    },
    {
        "inputdate": "2025-08-22",
        "blockdate": "2025-08-25",
        "const_name": "도로시설물 보수공사",
        "direction": "공항방향",
        "ieejung": "북인천영업소 광장부",
        "chadantime": "19:00~06:00",
        "chadan": "3차로, 4차로",
        "workers": 10,
        "signcar": 2,
        "workcar": 7,
        "employee": "한상열 수석",
        "employeephone": "010-8916-1430",
        "contractee": "상봉이앤씨",
        "sitemanager": "이래원 소장",
        "smcellphone": "010-3805-0234"
    },
    {
        "inputdate": "2025-08-24",
        "blockdate": "2025-08-19",
        "const_name": "테스트",
        "direction": "공항방향",
        "ieejung": "27.4~28.0",
        "chadantime": "08:00~19:00",
        "chadan": "1차로, 2차로",
        "workers": 4,
        "signcar": 1,
        "workcar": 3,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "테스트",
        "sitemanager": "테스트",
        "smcellphone": "010-2222-3333"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "차선도색공사",
        "direction": "양방향",
        "ieejung": "전구간",
        "chadantime": "09:00~18:00",
        "chadan": "1차로, 2차로, 3차로, 4차로",
        "workers": 13,
        "signcar": 3,
        "workcar": 4,
        "employee": "김도균",
        "employeephone": "01031172297",
        "contractee": "대한로드라인",
        "sitemanager": "문학영",
        "smcellphone": "01045376457"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "가변속도제한표지(VSL) 제조구매 철거 및 설치",
        "direction": "공항방향",
        "ieejung": "14.8k~12.5k (상부도로)",
        "chadantime": "09:00~17:00",
        "chadan": "3차로, 갓길",
        "workers": 9,
        "signcar": 4,
        "workcar": 4,
        "employee": "정호",
        "employeephone": "010-3301-1801",
        "contractee": "한일DNS",
        "sitemanager": "오동조 부장",
        "smcellphone": "010-8743-1564"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "010-9428-3658"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.6~13.4",
        "chadantime": "09:00~18:00",
        "chadan": "비상주차대",
        "workers": 4,
        "signcar": 0,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "010-8447-4659"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "설비유지관리용역",
        "direction": "공항방향",
        "ieejung": "34.0~36.3",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 1,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "대한곤돌라",
        "sitemanager": "홍지환",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "인천국제공항고속도로 도로포장상태조사 및 분석용역(2025년)",
        "direction": "양방향",
        "ieejung": "영종대교 상부도로 서울방향(10.8~14.5k), 서울방향(34.0~34.6k)",
        "chadantime": "09:00~18:00",
        "chadan": "1차로, 2차로, 3차로, 갓길",
        "workers": 8,
        "signcar": 3,
        "workcar": 2,
        "employee": "한상열",
        "employeephone": "010-89161430",
        "contractee": "(주)로드코리아",
        "sitemanager": "곽병석",
        "smcellphone": "010-4755-9142"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "공항방향",
        "ieejung": "10.0 ~ 15.0(하부도로)",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "010-9428-3658"
    },
    {
        "inputdate": "2025-08-25",
        "blockdate": "2025-08-26",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "10.0~15.0(하부도로)",
        "chadantime": "21:00~05:00",
        "chadan": "2차로",
        "workers": 4,
        "signcar": 5,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "010-9428-3658"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "가변속도제한표지(VSL) 제조구매 철거 및 설치",
        "direction": "공항방향",
        "ieejung": "13.0k~11.5k (상부도로), 10.3K~8.5K (본선)",
        "chadantime": "09:30~17:00",
        "chadan": "3차로, 4차로, 갓길",
        "workers": 8,
        "signcar": 3,
        "workcar": 5,
        "employee": "정호",
        "employeephone": "010-3301-1801",
        "contractee": "한일DNS",
        "sitemanager": "오동조 부장",
        "smcellphone": "010-8743-1564"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "교통사고 피해시설물 복구",
        "direction": "공항방향",
        "ieejung": "31.9K",
        "chadantime": "09:00~18:00",
        "chadan": "4차로, 갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "미추홀 클레임 서비스",
        "sitemanager": "강용구",
        "smcellphone": "010-5406-3848"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "교통사고 피해시설물 복구공사",
        "direction": "공항방향",
        "ieejung": "청라ICRA 1100",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 1,
        "employee": "김현호",
        "employeephone": "010-2755-7686",
        "contractee": "미추홀 클레임 서비스",
        "sitemanager": "강용구",
        "smcellphone": "010-5406-3848"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "33.5~36.5",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 8,
        "signcar": 2,
        "workcar": 3,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "백양엔지니어링",
        "sitemanager": "이명우",
        "smcellphone": "010-2392-5168"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "10.0~15.0(하부도로)",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 2,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "홍익기술단",
        "sitemanager": "이경수",
        "smcellphone": "010-9428-3658"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "영종, 방화대교 정밀안전진단",
        "direction": "양방향",
        "ieejung": "11.5~12.2",
        "chadantime": "09:00~18:00",
        "chadan": "1차로",
        "workers": 6,
        "signcar": 5,
        "workcar": 2,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "다음기술단",
        "sitemanager": "정건우",
        "smcellphone": "010-8447-4659"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "설비유지관리용역",
        "direction": "양방향",
        "ieejung": "34.0~36.3",
        "chadantime": "09:00~18:00",
        "chadan": "갓길",
        "workers": 4,
        "signcar": 1,
        "workcar": 1,
        "employee": "최종",
        "employeephone": "010-6797-5516",
        "contractee": "대한곤돌라",
        "sitemanager": "홍지환",
        "smcellphone": "010-2124-3794"
    },
    {
        "inputdate": "2025-08-26",
        "blockdate": "2025-08-27",
        "const_name": "차선도색공사",
        "direction": "양방향",
        "ieejung": "전구간",
        "chadantime": "09:00~18:00",
        "chadan": "1차로, 2차로, 3차로, 4차로",
        "workers": 13,
        "signcar": 3,
        "workcar": 4,
        "employee": "김도균",
        "employeephone": "01031172297",
        "contractee": "대한로드라인",
        "sitemanager": "문학영",
        "smcellphone": "01045376457"
    }
];